pollster/pages/urls.py
from django.urls import path

from .import views


urlpatterns = [
    path('', views.index, name='index'),

]

pollster/polls/urls.py
from django.urls import path

from .import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.createQue, name='create'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
]

pollster/pages/models.py
from django.db import models

# Create your models here.

pollster/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/polls/forms.py
from django import forms
from .models import Choice, Question


class CreateQuestion(forms.ModelForm):
    choice1 = forms.CharField(label='Choice 1', max_length=100, widget=forms.TextInput(
        attrs={"class": 'form-control'}))
    choice2 = forms.CharField(label='Choice 2', max_length=100, widget=forms.TextInput(
        attrs={"class": 'form-control'}))
    choice3 = forms.CharField(label='Choice 3', max_length=100, widget=forms.TextInput(
        attrs={"class": 'form-control'}))
    choice4 = forms.CharField(label='Choice 4', max_length=100, widget=forms.TextInput(
        attrs={"class": 'form-control'}))

    class Meta:
        model = Question
        fields = ['question_text', 'choice1',
                  'choice2', 'choice3', 'choice4', 'pub_date']
        widgets = {
            'question_text': forms.TextInput(attrs={'class': 'form-control'}),
        }

pollster/pages/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'pages/index.html')

pollster/polls/views.py
from django.shortcuts import render,redirect
from .models import Question, Choice
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse
from .forms import CreateQuestion

# Create your views here.


def createQue(request):
    if request.method == 'POST':
        form = CreateQuestion(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.save()
            new_choice1 = Choice(question=question,
                                 choice_text=form.cleaned_data['choice1']).save()
            new_choice2 = Choice(question=question,
                                 choice_text=form.cleaned_data['choice2']).save()
            new_choice3 = Choice(question=question,
                                 choice_text=form.cleaned_data['choice3']).save()
            new_choice4 = Choice(question=question,
                                 choice_text=form.cleaned_data['choice4']).save()
            return redirect('index')
    else:
        form = CreateQuestion(request.POST)
    context = {'form': form}
    return render(request, 'polls/create.html', context)


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist')
    context = {'question': question}
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice"},)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Pollster
        {% block title %}

        {% endblock title %}
    </title>
</head>

<body>
    {% include 'partials/_navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">

                {% block content %}

                {% endblock content %}

            </div>
        </div>
    </div>
</body>

</html>

pollster/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
<div class="card text-center">
    <div class="card-body">
        <h1>Welcome To Pollster</h1>
        <p>This is a Django Polling app</p>
        <a class="btn btn-primary" href="{% url 'polls:index' %}">View Available Polls</a>
    </div>
</div>
{% endblock content %}

pollster/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-dark mb-4">
    <div class="container">
        <a href="/" class="navbar-brand">Pollster</a>
        <a href="{% url 'polls:create' %}" class="navbar-brand">Create Poll</a>
    </div>
</nav>

pollster/templates/polls/create.html
{% extends 'base.html' %}

{% block content %}
<h1>Create A New Poll</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}


    <input class="btn btn-primary" type="submit" value="Create">
</form>
{% endblock content %}

pollster/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-outline-primary" href="{% url 'polls:index' %}">&#8592; Back</a>
<br>
<br>
<br>
<h1 class="text-center mb-3">{{question.question_text}}</h1>


{% if error_message %}
<p class="alert alert-danger"><strong>{{error_message}}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}

    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice" id="choice{{forloop.counter}}" class="form-check-input" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">
</form>

{% endblock content %}

pollster/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>

{% if latest_question_list %}

{% for question in latest_question_list %}
<div class="card mb-3">
    <div class="card-body">
        <p class="lead">{{question.question_text}}</p>
        <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote Now</a>
        <a class="btn btn-primary" href="{% url 'polls:results' question.id %}">Results</a>
    </div>
</div>

{% endfor %}


{% else %}
<p>No Polls available</p>
{% endif %}

{% endblock content %}

pollster/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mb-5">{{question.question_text}}</h1>
<ul class="list-group mb-5">

    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{choice.choice_text}} <span class="badge bg-primary float-end">
            {{choice.votes}} vote{{choice.votes | pluralize}}
        </span>
    </li>
    {% endfor %}

</ul>
<a class="btn btn-primary" href="{% url 'polls:index' %}">Back</a>
<a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote Again</a>
{% endblock content %}